general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = openrgb --config /home/neil/.config/OpenRGB --profile mem-sleep && loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on && ~/.config/hypr/scripts/rgb-resume.sh &
}

listener {
    timeout = 900                                 # 15min.
    on-timeout = playerctl -a status 2>/dev/null | grep -q Playing || ddcutil --bus 4 setvcp 10 0
    on-resume = ddcutil --bus 4 setvcp 10 50
}

listener {
    timeout = 1500                                # 25min
    on-timeout = playerctl -a status 2>/dev/null | grep -q Playing || loginctl lock-session   # lock screen when timeout has passed (skipped while music plays)
}

listener {
    timeout = 1800                                # 30min
    on-timeout = playerctl -a status 2>/dev/null | grep -q Playing || systemctl suspend   # suspend pc (skipped while music plays)
}
